### ISSUE TITLE
BCAT image MIME type in heroku

### ISSUE THREAD

**Issue by sjgllghr** [will-saunders/BCAT#20]
Heroku
<img width="326" alt="Screen Shot 2019-04-14 at 11 10 18 AM" src="https://user-images.githubusercontent.com/5944933/56097195-f3897f00-5ea5-11e9-884d-f5c64c49bce0.png">
Localhost
<img width="300" alt="Screen Shot 2019-04-14 at 11 10 29 AM" src="https://user-images.githubusercontent.com/5944933/56097197-f5ebd900-5ea5-11e9-917c-de5683f7c7e7.png">

**Comment by shankj3** [comment]
fixed w/ #23
